### ISSUE TITLE
customize topbar or add custom view above topbar

### ISSUE THREAD

**Issue by yerlanov14** [FleksySDK/VirtualKeyboardSDK#106]
Hello, I'm facing with the problem of customizing topbar. I want to fully replace topbar as shown in the screenshot.
![Keyboard](https://github.com/FleksySDK/VirtualKeyboardSDK/assets/133002322/fe750a52-1726-49d0-b02b-c023d3504dca)

Maximum what I can do is add 2 custom view on the left side of top bar and on the right side.
![photo_5355162050575324718_y](https://github.com/FleksySDK/VirtualKeyboardSDK/assets/133002322/2ac87343-c00c-44eb-8443-e0cc3a385e43)

I found that it is possible to add above topbar custom view in Android. Like shown in this screenshot.
<img width="664" alt="sss" src="https://github.com/FleksySDK/VirtualKeyboardSDK/assets/133002322/35984035-2e3e-4063-afad-4489207851eb">

Is it possible to do it for iOS?

**Comment by xevifar** [comment]
Hi @yerlanov14 , 

yes, you can do the same on iOS, you can replace the whole topbar by using this example: [OpenView](https://github.com/FleksySDK/VirtualKeyboardSDK/tree/main/Examples/OpenView/ios/KeyboardOpenView). The frame view is the same and you can define the height of your own top bar view.
