### ISSUE TITLE
Problems using Japanese in iOS

### ISSUE THREAD

**Issue by devlb** [FleksySDK/VirtualKeyboardSDK#107]
info:
  SDK： 4.21.0 、4.19.1
  iOS version:  15.4.1
  device: iPhone xr

bugs:
1. In Japanese QWERTY layout, prediction cannot appear at the top

2. It will freeze when typing, resulting in no response to any operation. Please see the video for details. Enter [watasi] in the Japanese QWERTY layout and it will appear

https://github.com/FleksySDK/VirtualKeyboardSDK/assets/12999919/f1b2d4af-985c-4693-a397-12fc291a6105

3.  "Certain characters need to be localized. For example, the currency symbol should be a YEN sign. Moreover, the """" should be replaced with 「」
Example in ""notes"" column. "

![截屏2024-02-23 16 34 05](https://github.com/FleksySDK/VirtualKeyboardSDK/assets/12999919/14c757d8-d845-4e8b-b9da-df71510abf5d)

4. About the Japanese (Kana input) keyboard, you need to add configuration to hide the prompts in the box
![截屏2024-02-23 16 37 23](https://github.com/FleksySDK/VirtualKeyboardSDK/assets/12999919/e272e791-d955-43fb-9eb2-e65292a9dac2)

**Comment by xevifar** [comment]
Hi @devlb , 
thank you for the reporting, I take the feedback and we add on the list to do it. 

Xevi

**Comment by devlb** [comment]
Please tell me when this bug can be fixed, our users are waiting

**Comment by xevifar** [comment]
Hi @devlb , this is on the list to be fixed but I cannot give you a date yet. 
If you need this urgently, could you send an email to customer.support@fleksy.com with your license to prioritise this issue ? 

Thank you

**Comment by xevifar** [comment]
Released the version [v4.25.0](https://docs.fleksy.com/sdk-ios/changelog/#v4250) that fixes these different issues.

@devlb you can update to this version and you should see the different fixes live.  Thank you for your patience.
