### ISSUE TITLE
Problem when using the keyboard inside other apps (No option for floating keyboard)

### ISSUE THREAD

**Issue by Sannusharma** [FleksySDK/VirtualKeyboardSDK#109]
There is no option to turn the keyboard into a floating keyboard.It covers the whole  screen and that causes issues. I cannot see the screen or select the field I'm supposed to type in. I frequently use whatsapp as a floating app or in a mini window inside other apps and sometimes inside games. I would really like an option to turn the keyboard into a floating keyboard to be easily able to use the keyboard inside other apps. Other keyboard apps like swiftkey and gboard are able to do this. I really like this keyboard and would love to use this on a daily basis but without these needed features it becomes useless. I really hope an update for this comes soon.

**Comment by xevifar** [comment]
Hello @Sannusharma ,

Thank you for your feedback but right now we do not have in the roadmap the floating keyboard. 
Best,
