### ISSUE TITLE
Japanese Flick keyboard issue

### ISSUE THREAD

**Issue by Undergrave91** [FleksySDK/VirtualKeyboardSDK#165]
Hello,

I'm learning Japanese as a Fleksy user so I've downloaded the flick keyboard available, but I quickly noticed an issue. 

Whenever you type a character another character appears. For example if you want to type  に (ni) you have to hold な (na) (middle of the keyboard) and flick to the left (as shown in the screenshot) however if you do that then の (no) appears (which would be the result of a downwards flick). This happens to all characters that need flicking. It seems the output for the left flicks is swapped with the down flicks and up is swapped with right.

Screenshot with explanation attached.

![jap keyb issue](https://github.com/user-attachments/assets/14ecdc43-ab2d-48f8-8299-959cfdc995fa)

**Comment by xevifar** [comment]
Hi @Undergrave91 , 

Thank you for the reporting. 
We should have this bug fixed on a version that we have on staging. Would it be possible for you to use this version
[Testflight FleksySDK Staging](https://testflight.apple.com/join/zOZEBpQ9) ? 
Let me know if this works for you. 
Thanks,

**Comment by Undergrave91** [comment]
Hello @xevifar,

I believe Testflight is an apple only app and thus I am unable to work with it. No problem though, I'm not in a hurry. If you are asking me to test then, unless there are alternatives... too bad haha.

Another issue I found is that Fleksy doesnt give enough Kanji recommendations which is necessary when typing Japanese. But I might be missing an option somewhere for that. Comparison given with Android keyboard below.

![jap keyb issue 2](https://github.com/user-attachments/assets/17ecc511-8696-48cb-82b2-4ba59d280da1)


Thanks for the quick reply.

**Comment by xevifar** [comment]
Hello @Undergrave91 , 

Sorry, I thought you were on Apple device.
We have all these different feedbacks fixed on our internal version, but it is not public yet. You can use the Android version that we have internally: [Android version](https://appdistribution.firebase.google.com/pub/i/f9ae23f7f30c9045). 

let me know if this works for you.

**Comment by Undergrave91** [comment]
Hello again,

This one works as expected :). I will be using that while I'm waiting for the next patch for additional features.

Beautiful work, thank you so much!
