### ISSUE TITLE
How to use PanelView inside Fleksy keyboard (iOS)

### ISSUE THREAD

**Issue by JainNkd** [FleksySDK/VirtualKeyboardSDK#38]
<img width="664" alt="Screenshot 2023-03-06 at 2 11 24 PM" src="https://user-images.githubusercontent.com/9711273/223060525-1467745b-e235-490d-953c-81aa561e7326.png">
I need to add some custom views as header and footer in the keyboard view. Please help us with how we can use the same for iOS. 

We need to integrate the TextField inside the header View too.

**Comment by xevifar** [comment]
Hi @JainNkd , 

We are gonna release the same behaviour for iOS in two weeks approximately. You can start using the Android one and when you finish with it the iOS will be waiting for you.

**Comment by JainNkd** [comment]
Hi Xevi,

Thanks for your response. 

Can you please update, is it possible to change the search icon with other icon PFA screen shoots?

<img width="347" alt="Screenshot 2023-04-03 at 1 32 39 PM" src="https://user-images.githubusercontent.com/9711273/230728248-f9ee7b00-5950-4510-9c00-b4aa487dac29.png">
<img width="346" alt="Screenshot 2023-04-03 at 9 00 35 AM" src="https://user-images.githubusercontent.com/9711273/230728252-5201d668-8dce-4e61-9f2a-8c023bbeb253.png">

**Comment by xevifar** [comment]
I will close this issue as it is already possible and it's working as expected. 
We provide an example of this beahviour here: [Example/KeyboardStyle](https://github.com/FleksySDK/VirtualKeyboardSDK/tree/main/examples/Style/iOS/KeyboardStyle)
