### ISSUE TITLE
[External] -[UIInputViewController needsInputModeSwitchKey] was called before a connection was established to the host application. This will produce an inaccurate result. Please make sure to call this after your primary view controller has been initialized.

### ISSUE THREAD

**Issue by JainNkd** [FleksySDK/VirtualKeyboardSDK#42]
[External] -[UIInputViewController needsInputModeSwitchKey] was called before a connection was established to the host application. This will produce an inaccurate result. Please make sure to call this after your primary view controller has been initialized. 

This issue appears after integration of https://github.com/FleksySDK/fleksy/tree/open-frame-example/examples in iOS

This message prints in debug logs and the keyboard crashes.

**Comment by xevifar** [comment]
Hi @JainNkd , 

Thank you for the reporting. 
We have updated the example that you mention removing a call not needed (```needsInputModeSwitchKey```), though, we were not able to reproduce the crash that you might experience. 

It would be helpful to understand a bit more:
- Does it happen all the time ? It crashes while debugging ?
- iOS version that you are using ? 
- Simulator or real device and model if possible.
- Do you have the crash logs ? 

Thank you,
