### ISSUE TITLE
Obfuscated (non-public) class names collide due to non-unique obfuscated naming (Fleksy Android)

### ISSUE THREAD

**Issue by artkat** [FleksySDK/VirtualKeyboardSDK#63]
The names of non-documented classes have been improperly obfuscated resulting in class names that easily collide with class names of other improperly obfuscated modules (names such as A, B, C).

In many cases, this would not be an issue. However, since I also use another 3rd party SDK/library which is similarly improperly obfuscated, I get many of such errors: _Duplicate class a.a found in modules jetified-fleksycore-release-4.4.12-runtime (co.thingthing.fleksycore:fleksycore-release:4.4.12) and jetified-otherlib-release-4.4.12-runtime (co.other.otherlib:otherlib-release:4.4.12)._

note to developers: You should always prefix all of your code in Java or other JVM languages with unique packages to create a unique [fully qualified name](https://en.wikipedia.org/wiki/Fully_qualified_name) because any two classes with the exact same fully qualified name will cause a build error. This happens because the JVM only uses the fully qualified name string, saved initially in a single table, to instantiate all the classes and interfaces in the system. If the table will have more than one entry for a class/interface, it won't know which one to choose.

Use Proguard's -repackageclasses option. [ProGuard Manual: Usage | Guardsquare](https://www.guardsquare.com/manual/configuration/usage)

**Comment by xevifar** [comment]
Hi @artkat , thank you for the reporting. 
We are looking into the issue that you reported.

**Comment by xevifar** [comment]
Solved version [4.5.2](https://docs.fleksy.com/sdk-android/changelog/#v452)
