### ISSUE TITLE
Copy in Messages will freeze openApp function.

### ISSUE THREAD

**Issue by fengyuxx** [FleksySDK/VirtualKeyboardSDK#73]
iPhone 11
iOS 17.1.1
FleksySDK-iOS 4.17.1

When the Fleksy keyboard is on, long press a message in the iOS system "Messages" app. After long press, the keyboard will be retracted, and then click "Copy" in the pop-up menu. The keyboard will then open automatically. At this time, clicking the "App" button in the keyboard cannot switch to the keyboardApps UI.
"openApp" is called in "triggerOpenApp" method, but nothing happens.

**Comment by xevifar** [comment]
Thanks for the reporting, we are looking into it and we will update it once we know more.
