### ISSUE TITLE
The appIcon for the Android alphabetical keyboard does not support RTL (Right-to-Left)

### ISSUE THREAD

**Issue by Howard2595** [FleksySDK/VirtualKeyboardSDK#78]
SDK Version: `fleksycore-release:4.3.8`

When the user switches to the Arabic language, the app icon in the top-left corner of the keyboard does not switch to the top-right corner.

Additionally, when configuring a background specifically for the alphabetical keyboard, the background color is not the configured color.
```kotlin
class SdkKeyboardService : KeyboardService() {
    // Omitting relevant code...

    private val keyboardBgColor: Int
        get() = R.color.keyboardBg

    override fun createConfiguration() =
        KeyboardConfiguration(
            style = KeyboardConfiguration.StyleConfiguration(
                forceTheme = SystemThemes.lightTheme.copy(background = keyboardBgColor)
            ),
            // Omitting relevant code...
        )

    // Omitting relevant code...
}
```
> Specified the background as keyboardBgColor, but the presented color in the subsequent interface is not this color.

**Comment by xevifar** [comment]
Hello @Howard2595 , 

Regarding the theme configuration, you might want to try to create the object [KeyboardTheme](https://docs.fleksy.com/sdk-android/api-reference-android/themeshelper/) which will enable you to customise the background theme. 

And for the switches to Arabic, if you need to move the top-left element to the top-right element you would be able to implement this by removing and adding the view to the leading or trailing view. 

Best,
