### ISSUE TITLE
[Android] Sample code for the addition of custom button on the Android layout

### ISSUE THREAD

**Issue by xevifar** [FleksySDK/VirtualKeyboardSDK#85]
**Description:** 
Sample code around how to add 2 magic buttons on left side of spacebar.

**Comment by samarthagarwalqb** [comment]
Hi Xevi, any updates on this one?

**Comment by xevifar** [comment]
> Hi Xevi, any updates on this one?

Hi @samarthagarwalqb , this is the next step to start with. As soon as we have it ready I will let you. Thank you for your patience.

**Comment by xevifar** [comment]
Hi @samarthagarwalqb , the example is here: [Example for customAction on Android](https://github.com/FleksySDK/VirtualKeyboardSDK/tree/main/Examples/CustomAction/android/KeyboardCustomAction)
