### ISSUE TITLE
Failed to download language.

### ISSUE THREAD

**Issue by DongDian455** [FleksySDK/VirtualKeyboardSDK#96]
## Environment
sdk version : 4.19.1

## Symptoms
![img_v3_026j_88964835-35aa-4d6d-bc18-0624fb7c12ag](https://github.com/FleksySDK/VirtualKeyboardSDK/assets/30856596/2e3da035-17f7-4333-8924-d9519906f263)

**Comment by devlb** [comment]
I have same problem

**Comment by DongDian455** [comment]
Why on earth hasn't this issue been fixed for such an extended period? It's absolutely unacceptable that the inability to download languages persists, making it utterly impossible to utilize any other language.

**Comment by xevifar** [comment]
This is fixed on the version [4.23.0](https://docs.fleksy.com/sdk-ios/changelog/#v4230). 
Could you try it and let me know ? 
Thx!
