### ISSUE TITLE
Unable to use swipe typing on Android with default "English US" language

### ISSUE THREAD

**Issue by limanup** [FleksySDK/VirtualKeyboardSDK#98]
Affected Fleksy SDK versions:

- v.4.5.3
- v.4.5.4
- v.4.5.5

Swipe typing is not working for default language "English US", but works for other "English" languages (e.g. "English CA") on Android devices. 
Tested on Pixel 6 and Pixel 7a devices.

**Comment by xevifar** [comment]
Hi @limanup , 
Could you share a bit more insights on this one ? 
I was trying to reproduce this using the [demo project](https://github.com/FleksySDK/VirtualKeyboardSDK/tree/main/Integration/Keyboard-Android) and I'm not able. 
Thank you

**Comment by limanup** [comment]
Hi @xevifar, the demo project is still on old Fleksy SDK version (4.0.1), please upgrade the SDK to the versions I mentioned above. The bug seems to only exist on the 3 versions mentioned above.

**Comment by xevifar** [comment]
Hello @limanup , 
Could you share your configuration ? 
We have been trying to reproduce this issue on these three versions and we are not able to reproduce, the swipe typing works on English US.

**Comment by limanup** [comment]
@xevifar I think I figured out what was wrong. We've always had the `automaticDownload = false` as our `KeyboardConfiguration.LanguageConfiguration`, the swipe typing works fine if I change it to `true`. We have the default `en-US` file (`resourceArchive-en-US.jet`) stored in `app/assets/encrypted/`. Do we need to update this jet file with a more up-to-date version? Just curious what was changed that we now have to enable `automaticDownload` to get swipe typing for the default en-US language? Thanks!

**Comment by xevifar** [comment]
Hi @limanup , ahh, good catch! 

This might be due to the old .jet for en-US does not support swipe typing for some reason. 
Could you just copy the last .jet that we have on the example ? That one should work too. 

We introduced the `automaticDownload` to keep the .jet files updated at the end user, so you do not need to worry about sending the improvements on all the languages that we are constantly making. 

Thank you for the reporting!

**Comment by xevifar** [comment]
@limanup , would it be possible for you to attach the .jet file here so we can analyse it and see why it did not work as expected ? 
Thank you

**Comment by limanup** [comment]
@xevifar that would be great! Please see attached. Thanks!
[assets.zip](https://github.com/FleksySDK/VirtualKeyboardSDK/files/14085943/assets.zip)

**Comment by limanup** [comment]
Yep, I just replaced the old one with one from the demo folder. @xevifar thanks for clarifying everything here!
